// Assignment code here


//click button and it generates a password

// after clicking prompts show up with criteria for password

// then i select what criteria to include in password

// length of at least 8 but no longer than 128

// when asked for character types to include 
//- i confirm whether or not to include lowercase, uppercase, numeric, and/or special characters

// once all prompts are answered a password is generated by either an alert or written on page 

// Get references to the #generate element
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
